[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
